### ISSUE TITLE
Support for tags?

### ISSUE THREAD

**Issue by staydecent** [ysbaddaden/pdoc#1]
Not sure if it's suppose to work now, or if not, is it planned to support Tags? Right now it seems to only grab descriptions ignoring things like: @param, @author, @return etc..

Thanks, like where this is going. PHPDoc and others are so giant and ugly, takes too much work to make the outputted docs to look they way I want.

**Comment by ysbaddaden** [comment]
I'm not planning to support javadoc-like tags. pdoc is inspired by ruby's rdoc, and will stay far away from phpdoc syntax.

There is thus no brief, no tags, etc. Just a plain description --with a few useful modifiers to force things (like `:namespace: my\ns`). The idea is to force nothing upon the user, and to be able to write as you wish (ie. naturally, like a real manual, or whatever else).

Here are a few examples:

```
# returns true if string is blank
function is_blank() { ... }

# Checks something.
# 
# = Params 
# 
# - +$a+ - first param;
# - +$b+ - second param.
# 
# = Returns
# 
# Returns true if the check succeeds. False otherwise.
function check_something($a, $b) { ... }
```
